[build]
publish = "public"

[functions."feeds-update"]
  schedule = "@hourly"

[[redirects]]
from = "/admin"
to = "/admin.html"
status = 301

[[redirects]]
from = "/login"
to = "/admin.html"
status = 301