[build]
publish = "public"

[functions."feeds-update"]
  schedule = "@hourly"

[[redirects]]
from = "/admin"
to = "/admin.html"
status = 301

[[redirects]]
from = "/login"
to = "/admin.html"
status = 301

# Endereço usado durante o desenvolvimento do layout novo
[[redirects]]
from = "/feed.html"
to = "/"
status = 301
force = true
