backend:
  name: git-gateway
  branch: main

media_folder: "assets/images/uploads"
public_folder: "/assets/images/uploads"

collections:
  - name: "momentos"
    label: "Momentos"
    files:
      - label: "Lista de Momentos"
        name: "momentos"
        file: "assets/data/momentos.json"
        format: "json"
        fields:
          - label: "Momentos"
            name: "items"
            widget: "list"
            fields:
              - { label: "Título", name: "titulo", widget: "string" }
              - { 
                  label: "Categoria", 
                  name: "categoria", 
                  widget: "select",
                  options: ["família", "passeio", "lives", "inesquecíveis", "anual", "amigos", "viagens", "diversos"]
                }
              - { label: "Imagem", name: "imagem", widget: "image" }